// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wiaqacbravoqmsqaihzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpYXFhY2JyYXZvcW1zcWFpaHpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4NjE3MzgsImV4cCI6MjA1MDQzNzczOH0.Y1Ju2y4j8R3IsCFJCxkKLl44gZZb8BSoSK8ko0Dgg5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);